// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmeusvwsruatxaqwehjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZXVzdndzcnVhdHhhcXdlaGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MjQ4NjUsImV4cCI6MjA1NzAwMDg2NX0.64QjNczifcRY89PDIJ69L2g4nvpK5GWfUUQ5IvbAibc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);